### ISSUE TITLE
Too many requests at once

### ISSUE THREAD

**Issue by defau1t** [jpas/junk#2]
Might suggest rate limiting, can only do 50 IDs at once

```
spotify.errors.HTTPException: Bad Request (status code: 400): Max 50 IDs at once
```

**Comment by jpas** [comment]
Which spotify request are you getting this on? My guess is the `save_albums` call.

**Comment by defau1t** [comment]
Yes it's save_albums.
Here's the full tracelog:
```
Traceback (most recent call last):
  File "to-spotify.py", line 94, in <module>
    s_library.save_albums(*s_albums)
  File "/home/defau1t/.local/share/virtualenvs/tmp-6quIM8pf/lib/python3.6/site-p
ackages/spotify/sync/models.py", line 42, in wrapper
    func(self, *args, **kwargs)
  File "/home/defau1t/.local/share/virtualenvs/tmp-6quIM8pf/lib/python3.6/site-packages/spotify/sync/thread.py", line 73, in run_coro
    raise err
  File "/home/defau1t/.local/share/virtualenvs/tmp-6quIM8pf/lib/python3.6/site-packages/spotify/models/library.py", line 111, in save_albums
    await self.user.http.save_albums(','.join(_albums))
  File "/home/defau1t/.local/share/virtualenvs/tmp-6quIM8pf/lib/python3.6/site-packages/spotify/http.py", line 170, in request
    raise HTTPException(r, data)
spotify.errors.HTTPException: Bad Request (status code: 400): Max 50 IDs at once
```

**Comment by jpas** [comment]
I added a fix, could you test it to make sure it actually works as I don't have an artist with that many albums.

**Comment by defau1t** [comment]
Yup it works! Thanks
